# Config file for mtd

update_interval = 60

[web]
debug_mode = true
unix_socket = "mtd.http.socket"
http_port = "9000"

# Plugins

[plugins.nginx]
plugin = "nginx"
logfile = "/var/log/nginx/access.log"
#logformat

[plugins.glances]
plugin = "zmq"
host = "127.0.0.1"
port = 5678


# Logging configuration

[logging]
disable_existing_loggers = false
version = 1

[logging.root]
handlers = [ "console",]
level = "DEBUG"

[logging.formatters.colored]
"()" = "colorlog.ColoredFormatter"
datefmt = "%b %d %H:%M:%S"
format = "%(asctime)s.%(msecs)03d %(bold)s%(log_color)s[%(levelname)4.4s]%(reset)s (%(threadName)s) %(name)s: %(message_log_color)s%(message)s"

[logging.formatters.simple]
format = "%(asctime)s.%(msecs)d - %(name)s - %(levelname)s - %(message)s"

[logging.handlers.console]
class = "logging.StreamHandler"
formatter = "colored"
level = "DEBUG"
stream = "ext://sys.stdout"

[logging.handlers.simple]
class = "logging.StreamHandler"
formatter = "simple"
level = "DEBUG"
stream = "ext://sys.stdout"

[logging.loggers.asyncio]
level = "DEBUG"

[logging.loggers."aiohttp.access"]
level = "DEBUG"

[logging.loggers.mtd]
level = "INFO"

[logging.loggers."mtd.pubsub"]
level = "DEBUG"

[logging.formatters.colored.log_colors]
CRITICAL = "red,bg_white"
DEBUG = "cyan"
ERROR = "red"
INFO = "green"
WARNING = "yellow"

[logging.formatters.colored.secondary_log_colors.message]
CRITICAL = "bold_red"
DEBUG = "bold"
ERROR = "bold_red"
INFO = "bold"
WARNING = "bold_yellow"
